# Thank you for using MobLoot!

PermissionDenied: '&8[ &c:( &8] &7You do not have permission to do that!'

# Max amount of custom items that can be dropped (overides 100% drop rate)
MaxItemDrops: 8

# Only one of these vaules can be true
MobSpawner:
  # Only drop MobLoot items from mobs spawn by a Mob Spawner
  OnlyFromSpawners: false
  # Disable MobLoot Drops from mobs spawn by a Mob Spawner
  NotFromSpawners: false

ShiftClick: true

Logger: true

Disable:
  Worlds:
    - 'name-of-a-world-here'

# Requires Vault
MoneySettings:
  RewardMoney: true
  DecimalPlaces: 2

  # Note the "00", meaning exactly two decimal places.
  # If you use "#.##" (# means "optional" digit), it will drop trailing zeroes
  DisplayFormat: '#,###,##0.00'

  # 2 = $2.51 , 1 = $2.5, 0 = $2
  DisableMessage: false
  # Variables:
  #   %uentity% - Displays entitys name in upper case
  #   %lentity% - Displays entitys name in lower case
  #   %entity% - Displays entitys with first letter capitalized
  #   %money% - Displays money value
  Message: '&8[&dMob Loot&8] &7You recived &a%money% &7for killing a &a%lentity%&7!'

Mobs:
  Bat:
    Money: 0.5
    DropDefaultItems: true
    MaxItemDrops: 8
  Blaze:
    Money: 0.5-1.5
    DropDefaultItems: true
    MaxItemDrops: 8
  CaveSpider:
    Money: 1-2
    DropDefaultItems: true
    MaxItemDrops: 8
  Chicken:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Cow:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Creeper:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  EnderDragon:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Enderman:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Endermite:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Ghast:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Giant:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Guardian:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Horse:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  IronGolem:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  MagmaCube:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  MushroomCow:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Ocelot:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Pig:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Rabbit:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Sheep:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Silverfish:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Shulker:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Skeleton:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Slime:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Snowman:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Spider:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Squid:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Villager:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Witch:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Wither:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Wolf:
    Money: 0-1
    DropDefaultItems:
    MaxItemDrops: 8
  Zombie:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  PigZombie:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8
  Player:
    Money: 2-3
    DropDefaultItems: true
    MaxItemDrops: 8
  PolarBear:
    Money: 0-1
    DropDefaultItems: true
    MaxItemDrops: 8

  AllBossMobs:
    Ignore: {}
  AllHostileMobs:
    Ignore: {}
  AllNeutralMobs:
    Ignore: {}
  AllPassiveMobs:
    Ignore: {}
  AllTamableMobs:
    Ignore: {}
  AllUtilityMobs:
    Ignore: {}


UnknownSpawnCause:
  DropItems: true
  ConsoleMessage: false