# Thank you for testing MobLootV2 Beta!
PermissionDenied: '&8[ &c:( &8] &7You do not have permission to do that!'

# Decimal Places of randomly generated number when dropping items
RandomDecimalPlaces: 5

Logger: true

# Requires Vault
MoneySettings:
  RewardMoney: true
  DecimalPlaces: 2

  # Note the "00", meaning exactly two decimal places.
  # If you use "#.##" (# means "optional" digit), it will drop trailing zeroes
  DisplayFormat: '#,###,##0.00'

  DisableMessage: false
  # Variables:
  #   %uentity% - Displays entity's name in upper case
  #   %lentity% - Displays entity's name in lower case
  #   %entity% - Displays entity's with first letter capitalized
  #   %money% - Displays money value
  Message: '&8[&dMob Loot&8] &7You recived &a%money% &7for killing a &a%lentity%&7!'
